import User from "../../../images/avatar/b-sm.jpg";
import User2 from "../../../images/avatar/c-sm.jpg";
import User3 from "../../../images/avatar/a-sm.jpg";
import User4 from "../../../images/avatar/d-sm.jpg";

export const userData = [
  {
    id: 1,
    avatarBg: "purple",
    desiredClassEntry:"Year7",
    session:"2024",
    surname: "Olashore",
    firstname: "Kehide",
    othername: "Dayo",
    dob: "10 Aug, 1975",
    gender: "male",
    siblings: "no",
    examLocation: "Abuja",
    currentSchoolName: "PREPARATORY SCHOOL",
    currentSchoolAddress: "ABUJA PREPARATORY SCHOOL, WUSE 2 ABUJA",
    PresentClass: "Year 5",
    fathersName: "John Doe",
    fathersEmail: "johndoe@yahoo.com",
    fathersPhone: "818474958",
    mothersName: "Jane Doe",
    mothersEmail: "Janedoe@email.com",
    mothersPhone: "818474958",
    parentAddress: "Plot 500 Alusa, Lagos",
    refreeName: "Kunle Afolayan",
    refreeNumber: "8069854223",
    refreeAddress: "2337 Kildeer Drive",
    howKnowSchool: "Instagram",
    birthCertificate: User3,
    passportPhotograph: User,
    schoolResult: User2,
    evidencePayment: User4,
  },
  {
    id: 2,
    avatarBg: "purple",
    desiredClassEntry:"Year5",
    session:"2024",
    surname: "Adekunle",
    firstname: "Adeola",
    othername: "Olusegun",
    dob: "9 Sep, 1999",
    gender: "female",
    siblings: "yes",
    examLocation: "Lagos",
    currentSchoolName: "Convetry SCHOOL",
    currentSchoolAddress: "Lagos PREPARATORY SCHOOL, Surulere 2 Aguda.",
    PresentClass: "Basic 1",
    fathersName: "Doe John",
    fathersEmail: "doe@yahoo.com",
    fathersPhone: "8109074958",
    mothersName: "Doe Jane",
    mothersEmail: "Jane@email.com",
    mothersPhone: "8184123958",
    parentAddress: "Plot 100 Olatubusun, LAdipo Lagos",
    refreeName: "Bayo Salubata",
    refreeNumber: "806987452",
    refreeAddress: "337 rodeo Drive",
    howKnowSchool: "siblings",
    birthCertificate: User3,
    passportPhotograph: User,
    schoolResult: User2,
    evidencePayment: User4,
  },
  {
    id: 3,
    desiredClassEntry:"Year5",
    session:"2024",
    surname: "Adekunle",
    firstname: "Adeola",
    othername: "Olusegun",
    dob: "9 Sep, 1999",
    gender: "female",
    siblings: "yes",
    examLocation: "Lagos",
    currentSchoolName: "Convetry SCHOOL",
    currentSchoolAddress: "Lagos PREPARATORY SCHOOL, Surulere 2 Aguda.",
    PresentClass: "Basic 1",
    fathersName: "Doe John",
    fathersEmail: "doe@yahoo.com",
    fathersPhone: "8109074958",
    mothersName: "Doe Jane",
    mothersEmail: "Jane@email.com",
    mothersPhone: "8184123958",
    parentAddress: "Plot 100 Olatubusun, LAdipo Lagos",
    refreeName: "Bayo Salubata",
    refreeNumber: "806987452",
    refreeAddress: "337 rodeo Drive",
    howKnowSchool: "siblings",
    birthCertificate: User3,
    passportPhotograph: User,
    schoolResult: User2,
    evidencePayment: User4,
  },
  {
    id: 4,
    avatarBg: "danger",
    desiredClassEntry:"Year5",
    session:"2024",
    surname: "Adekunle",
    firstname: "Adeola",
    othername: "Olusegun",
    dob: "9 Sep, 1999",
    gender: "female",
    siblings: "yes",
    examLocation: "Lagos",
    currentSchoolName: "Convetry SCHOOL",
    currentSchoolAddress: "Lagos PREPARATORY SCHOOL, Surulere 2 Aguda.",
    PresentClass: "Basic 1",
    fathersName: "Doe John",
    fathersEmail: "doe@yahoo.com",
    fathersPhone: "8109074958",
    mothersName: "Doe Jane",
    mothersEmail: "Jane@email.com",
    mothersPhone: "8184123958",
    parentAddress: "Plot 100 Olatubusun, LAdipo Lagos",
    refreeName: "Bayo Salubata",
    refreeNumber: "806987452",
    refreeAddress: "337 rodeo Drive",
    howKnowSchool: "siblings",
    birthCertificate: User3,
    passportPhotograph: User,
    schoolResult: User2,
    evidencePayment: User4,
  },
  {
    id: 5,
    avatarBg: "purple",
    desiredClassEntry:"Year5",
    session:"2024",
    surname: "Adekunle",
    firstname: "Adeola",
    othername: "Olusegun",
    dob: "9 Sep, 1999",
    gender: "female",
    siblings: "yes",
    examLocation: "Lagos",
    currentSchoolName: "Convetry SCHOOL",
    currentSchoolAddress: "Lagos PREPARATORY SCHOOL, Surulere 2 Aguda.",
    PresentClass: "Basic 1",
    fathersName: "Doe John",
    fathersEmail: "doe@yahoo.com",
    fathersPhone: "8109074958",
    mothersName: "Doe Jane",
    mothersEmail: "Jane@email.com",
    mothersPhone: "8184123958",
    parentAddress: "Plot 100 Olatubusun, LAdipo Lagos",
    refreeName: "Bayo Salubata",
    refreeNumber: "806987452",
    refreeAddress: "337 rodeo Drive",
    howKnowSchool: "siblings",
    birthCertificate: User3,
    passportPhotograph: User,
    schoolResult: User2,
    evidencePayment: User4,
  },
  {
    id: 6,
    avatarBg: "primary",
    desiredClassEntry:"Year5",
    session:"2024",
    surname: "Adekunle",
    firstname: "Adeola",
    othername: "Olusegun",
    dob: "9 Sep, 1999",
    gender: "female",
    siblings: "yes",
    examLocation: "Lagos",
    currentSchoolName: "Convetry SCHOOL",
    currentSchoolAddress: "Lagos PREPARATORY SCHOOL, Surulere 2 Aguda.",
    PresentClass: "Basic 1",
    fathersName: "Doe John",
    fathersEmail: "doe@yahoo.com",
    fathersPhone: "8109074958",
    mothersName: "Doe Jane",
    mothersEmail: "Jane@email.com",
    mothersPhone: "8184123958",
    parentAddress: "Plot 100 Olatubusun, LAdipo Lagos",
    refreeName: "Bayo Salubata",
    refreeNumber: "806987452",
    refreeAddress: "337 rodeo Drive",
    howKnowSchool: "siblings",
    birthCertificate: User3,
    passportPhotograph: User,
    schoolResult: User2,
    evidencePayment: User4,
  },
  {
    id: 7,
    avatarBg: "warning",
    desiredClassEntry:"Year5",
    session:"2024",
    surname: "Adekunle",
    firstname: "Adeola",
    othername: "Olusegun",
    dob: "9 Sep, 1999",
    gender: "female",
    siblings: "yes",
    examLocation: "Lagos",
    currentSchoolName: "Convetry SCHOOL",
    currentSchoolAddress: "Lagos PREPARATORY SCHOOL, Surulere 2 Aguda.",
    PresentClass: "Basic 1",
    fathersName: "Doe John",
    fathersEmail: "doe@yahoo.com",
    fathersPhone: "8109074958",
    mothersName: "Doe Jane",
    mothersEmail: "Jane@email.com",
    mothersPhone: "8184123958",
    parentAddress: "Plot 100 Olatubusun, LAdipo Lagos",
    refreeName: "Bayo Salubata",
    refreeNumber: "806987452",
    refreeAddress: "337 rodeo Drive",
    howKnowSchool: "siblings",
    birthCertificate: User3,
    passportPhotograph: User,
    schoolResult: User2,
    evidencePayment: User4,
  },
  {
    id: 8,
    avatarBg: "success",
    desiredClassEntry:"Year5",
    session:"2024",
    surname: "Adekunle",
    firstname: "Adeola",
    othername: "Olusegun",
    dob: "9 Sep, 1999",
    gender: "female",
    siblings: "yes",
    examLocation: "Lagos",
    currentSchoolName: "Convetry SCHOOL",
    currentSchoolAddress: "Lagos PREPARATORY SCHOOL, Surulere 2 Aguda.",
    PresentClass: "Basic 1",
    fathersName: "Doe John",
    fathersEmail: "doe@yahoo.com",
    fathersPhone: "8109074958",
    mothersName: "Doe Jane",
    mothersEmail: "Jane@email.com",
    mothersPhone: "8184123958",
    parentAddress: "Plot 100 Olatubusun, LAdipo Lagos",
    refreeName: "Bayo Salubata",
    refreeNumber: "806987452",
    refreeAddress: "337 rodeo Drive",
    howKnowSchool: "siblings",
    birthCertificate: User3,
    passportPhotograph: User,
    schoolResult: User2,
    evidencePayment: User4,
  },
  {
    id: 9,
    avatarBg: "purple",
    desiredClassEntry:"Year5",
    session:"2024",
    surname: "Adekunle",
    firstname: "Adeola",
    othername: "Olusegun",
    dob: "9 Sep, 1999",
    gender: "female",
    siblings: "yes",
    examLocation: "Lagos",
    currentSchoolName: "Convetry SCHOOL",
    currentSchoolAddress: "Lagos PREPARATORY SCHOOL, Surulere 2 Aguda.",
    PresentClass: "Basic 1",
    fathersName: "Doe John",
    fathersEmail: "doe@yahoo.com",
    fathersPhone: "8109074958",
    mothersName: "Doe Jane",
    mothersEmail: "Jane@email.com",
    mothersPhone: "8184123958",
    parentAddress: "Plot 100 Olatubusun, LAdipo Lagos",
    refreeName: "Bayo Salubata",
    refreeNumber: "806987452",
    refreeAddress: "337 rodeo Drive",
    howKnowSchool: "siblings",
    birthCertificate: User3,
    passportPhotograph: User,
    schoolResult: User2,
    evidencePayment: User4,
  },
  {
    id: 10,
    avatarBg: "purple",
    desiredClassEntry:"Year5",
    session:"2024",
    surname: "Adekunle",
    firstname: "Adeola",
    othername: "Olusegun",
    dob: "9 Sep, 1999",
    gender: "female",
    siblings: "yes",
    examLocation: "Lagos",
    currentSchoolName: "Convetry SCHOOL",
    currentSchoolAddress: "Lagos PREPARATORY SCHOOL, Surulere 2 Aguda.",
    PresentClass: "Basic 1",
    fathersName: "Doe John",
    fathersEmail: "doe@yahoo.com",
    fathersPhone: "8109074958",
    mothersName: "Doe Jane",
    mothersEmail: "Jane@email.com",
    mothersPhone: "8184123958",
    parentAddress: "Plot 100 Olatubusun, LAdipo Lagos",
    refreeName: "Bayo Salubata",
    refreeNumber: "806987452",
    refreeAddress: "337 rodeo Drive",
    howKnowSchool: "siblings",
    birthCertificate: User3,
    passportPhotograph: User,
    schoolResult: User2,
    evidencePayment: User4,
  },
  {
    id: 11,
    avatarBg: "pink",
    desiredClassEntry:"Year5",
    session:"2024",
    surname: "Adekunle",
    firstname: "Adeola",
    othername: "Olusegun",
    dob: "9 Sep, 1999",
    gender: "female",
    siblings: "yes",
    examLocation: "Lagos",
    currentSchoolName: "Convetry SCHOOL",
    currentSchoolAddress: "Lagos PREPARATORY SCHOOL, Surulere 2 Aguda.",
    PresentClass: "Basic 1",
    fathersName: "Doe John",
    fathersEmail: "doe@yahoo.com",
    fathersPhone: "8109074958",
    mothersName: "Doe Jane",
    mothersEmail: "Jane@email.com",
    mothersPhone: "8184123958",
    parentAddress: "Plot 100 Olatubusun, LAdipo Lagos",
    refreeName: "Bayo Salubata",
    refreeNumber: "806987452",
    refreeAddress: "337 rodeo Drive",
    howKnowSchool: "siblings",
    birthCertificate: User3,
    passportPhotograph: User,
    schoolResult: User2,
    evidencePayment: User4,
  },
  {
    id: 12,
    avatarBg: "secondary",
    desiredClassEntry:"Year5",
    session:"2024",
    surname: "Adekunle",
    firstname: "Adeola",
    othername: "Olusegun",
    dob: "9 Sep, 1999",
    gender: "female",
    siblings: "yes",
    examLocation: "Lagos",
    currentSchoolName: "Convetry SCHOOL",
    currentSchoolAddress: "Lagos PREPARATORY SCHOOL, Surulere 2 Aguda.",
    PresentClass: "Basic 1",
    fathersName: "Doe John",
    fathersEmail: "doe@yahoo.com",
    fathersPhone: "8109074958",
    mothersName: "Doe Jane",
    mothersEmail: "Jane@email.com",
    mothersPhone: "8184123958",
    parentAddress: "Plot 100 Olatubusun, LAdipo Lagos",
    refreeName: "Bayo Salubata",
    refreeNumber: "806987452",
    refreeAddress: "337 rodeo Drive",
    howKnowSchool: "siblings",
    birthCertificate: User3,
    passportPhotograph: User,
    schoolResult: User2,
    evidencePayment: User4,
  },
  {
    id: 13,
    avatarBg: "pink",
    desiredClassEntry:"Year5",
    session:"2024",
    surname: "Adekunle",
    firstname: "Adeola",
    othername: "Olusegun",
    dob: "9 Sep, 1999",
    gender: "female",
    siblings: "yes",
    examLocation: "Lagos",
    currentSchoolName: "Convetry SCHOOL",
    currentSchoolAddress: "Lagos PREPARATORY SCHOOL, Surulere 2 Aguda.",
    PresentClass: "Basic 1",
    fathersName: "Doe John",
    fathersEmail: "doe@yahoo.com",
    fathersPhone: "8109074958",
    mothersName: "Doe Jane",
    mothersEmail: "Jane@email.com",
    mothersPhone: "8184123958",
    parentAddress: "Plot 100 Olatubusun, LAdipo Lagos",
    refreeName: "Bayo Salubata",
    refreeNumber: "806987452",
    refreeAddress: "337 rodeo Drive",
    howKnowSchool: "siblings",
    birthCertificate: User3,
    passportPhotograph: User,
    schoolResult: User2,
    evidencePayment: User4,
  },
  {
    id: 14,
    avatarBg: "blue",
    desiredClassEntry:"Year5",
    session:"2024",
    surname: "Adekunle",
    firstname: "Adeola",
    othername: "Olusegun",
    dob: "9 Sep, 1999",
    gender: "female",
    siblings: "yes",
    examLocation: "Lagos",
    currentSchoolName: "Convetry SCHOOL",
    currentSchoolAddress: "Lagos PREPARATORY SCHOOL, Surulere 2 Aguda.",
    PresentClass: "Basic 1",
    fathersName: "Doe John",
    fathersEmail: "doe@yahoo.com",
    fathersPhone: "8109074958",
    mothersName: "Doe Jane",
    mothersEmail: "Jane@email.com",
    mothersPhone: "8184123958",
    parentAddress: "Plot 100 Olatubusun, LAdipo Lagos",
    refreeName: "Bayo Salubata",
    refreeNumber: "806987452",
    refreeAddress: "337 rodeo Drive",
    howKnowSchool: "siblings",
    birthCertificate: User3,
    passportPhotograph: User,
    schoolResult: User2,
    evidencePayment: User4,
  },
  {
    id: 15,
    avatarBg: "pink",
    desiredClassEntry:"Year5",
    session:"2024",
    surname: "Adekunle",
    firstname: "Adeola",
    othername: "Olusegun",
    dob: "9 Sep, 1999",
    gender: "female",
    siblings: "yes",
    examLocation: "Lagos",
    currentSchoolName: "Convetry SCHOOL",
    currentSchoolAddress: "Lagos PREPARATORY SCHOOL, Surulere 2 Aguda.",
    PresentClass: "Basic 1",
    fathersName: "Doe John",
    fathersEmail: "doe@yahoo.com",
    fathersPhone: "8109074958",
    mothersName: "Doe Jane",
    mothersEmail: "Jane@email.com",
    mothersPhone: "8184123958",
    parentAddress: "Plot 100 Olatubusun, LAdipo Lagos",
    refreeName: "Bayo Salubata",
    refreeNumber: "806987452",
    refreeAddress: "337 rodeo Drive",
    howKnowSchool: "siblings",
    birthCertificate: User3,
    passportPhotograph: User,
    schoolResult: User2,
    evidencePayment: User4,
  },
  {
    id: 16,
    avatarBg: "blue",
    desiredClassEntry:"Year5",
    session:"2024",
    surname: "Adekunle",
    firstname: "Adeola",
    othername: "Olusegun",
    dob: "9 Sep, 1999",
    gender: "female",
    siblings: "yes",
    examLocation: "Lagos",
    currentSchoolName: "Convetry SCHOOL",
    currentSchoolAddress: "Lagos PREPARATORY SCHOOL, Surulere 2 Aguda.",
    PresentClass: "Basic 1",
    fathersName: "Doe John",
    fathersEmail: "doe@yahoo.com",
    fathersPhone: "8109074958",
    mothersName: "Doe Jane",
    mothersEmail: "Jane@email.com",
    mothersPhone: "8184123958",
    parentAddress: "Plot 100 Olatubusun, LAdipo Lagos",
    refreeName: "Bayo Salubata",
    refreeNumber: "806987452",
    refreeAddress: "337 rodeo Drive",
    howKnowSchool: "siblings",
    birthCertificate: User3,
    passportPhotograph: User,
    schoolResult: User2,
    evidencePayment: User4,
  },
  {
    id: 17,
    avatarBg: "secondary",
    desiredClassEntry:"Year5",
    session:"2024",
    surname: "Adekunle",
    firstname: "Adeola",
    othername: "Olusegun",
    dob: "9 Sep, 1999",
    gender: "female",
    siblings: "yes",
    examLocation: "Lagos",
    currentSchoolName: "Convetry SCHOOL",
    currentSchoolAddress: "Lagos PREPARATORY SCHOOL, Surulere 2 Aguda.",
    PresentClass: "Basic 1",
    fathersName: "Doe John",
    fathersEmail: "doe@yahoo.com",
    fathersPhone: "8109074958",
    mothersName: "Doe Jane",
    mothersEmail: "Jane@email.com",
    mothersPhone: "8184123958",
    parentAddress: "Plot 100 Olatubusun, LAdipo Lagos",
    refreeName: "Bayo Salubata",
    refreeNumber: "806987452",
    refreeAddress: "337 rodeo Drive",
    howKnowSchool: "siblings",
    birthCertificate: User3,
    passportPhotograph: User,
    schoolResult: User2,
    evidencePayment: User4,
  },
  {
    id: 18,
    avatarBg: "warning",
    desiredClassEntry:"Year5",
    session:"2024",
    surname: "Adekunle",
    firstname: "Adeola",
    othername: "Olusegun",
    dob: "9 Sep, 1999",
    gender: "female",
    siblings: "yes",
    examLocation: "Lagos",
    currentSchoolName: "Convetry SCHOOL",
    currentSchoolAddress: "Lagos PREPARATORY SCHOOL, Surulere 2 Aguda.",
    PresentClass: "Basic 1",
    fathersName: "Doe John",
    fathersEmail: "doe@yahoo.com",
    fathersPhone: "8109074958",
    mothersName: "Doe Jane",
    mothersEmail: "Jane@email.com",
    mothersPhone: "8184123958",
    parentAddress: "Plot 100 Olatubusun, LAdipo Lagos",
    refreeName: "Bayo Salubata",
    refreeNumber: "806987452",
    refreeAddress: "337 rodeo Drive",
    howKnowSchool: "siblings",
    birthCertificate: User3,
    passportPhotograph: User,
    schoolResult: User2,
    evidencePayment: User4,
  },
  {
    id: 19,
    avatarBg: "secondary",
    desiredClassEntry:"Year5",
    session:"2024",
    surname: "Adekunle",
    firstname: "Adeola",
    othername: "Olusegun",
    dob: "9 Sep, 1999",
    gender: "female",
    siblings: "yes",
    examLocation: "Lagos",
    currentSchoolName: "Convetry SCHOOL",
    currentSchoolAddress: "Lagos PREPARATORY SCHOOL, Surulere 2 Aguda.",
    PresentClass: "Basic 1",
    fathersName: "Doe John",
    fathersEmail: "doe@yahoo.com",
    fathersPhone: "8109074958",
    mothersName: "Doe Jane",
    mothersEmail: "Jane@email.com",
    mothersPhone: "8184123958",
    parentAddress: "Plot 100 Olatubusun, LAdipo Lagos",
    refreeName: "Bayo Salubata",
    refreeNumber: "806987452",
    refreeAddress: "337 rodeo Drive",
    howKnowSchool: "siblings",
    birthCertificate: User3,
    passportPhotograph: User,
    schoolResult: User2,
    evidencePayment: User4,
  },
  {
    id: 20,
    avatarBg: "warning",
    desiredClassEntry:"Year5",
    session:"2024",
    surname: "Adekunle",
    firstname: "Adeola",
    othername: "Olusegun",
    dob: "9 Sep, 1999",
    gender: "female",
    siblings: "yes",
    examLocation: "Lagos",
    currentSchoolName: "Convetry SCHOOL",
    currentSchoolAddress: "Lagos PREPARATORY SCHOOL, Surulere 2 Aguda.",
    PresentClass: "Basic 1",
    fathersName: "Doe John",
    fathersEmail: "doe@yahoo.com",
    fathersPhone: "8109074958",
    mothersName: "Doe Jane",
    mothersEmail: "Jane@email.com",
    mothersPhone: "8184123958",
    parentAddress: "Plot 100 Olatubusun, LAdipo Lagos",
    refreeName: "Bayo Salubata",
    refreeNumber: "806987452",
    refreeAddress: "337 rodeo Drive",
    howKnowSchool: "siblings",
    birthCertificate: User3,
    passportPhotograph: User,
    schoolResult: User2,
    evidencePayment: User4,
  },
];

export const notes = [
  {
    id: 1,
    text: "Aproin at metus et dolor tincidunt feugiat eu id quam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean sollicitudin non nunc vel pharetra.",
    date: "November 18, 2019",
    time: "5:34",
    company: "Softnio",
  },
  {
    id: 2,
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi eleifend libero semper metus aliquam tempus. Sed efficitur elit et ligula lobortis",
    date: "December 27, 2019",
    time: "7:00",
    company: "Softnio",
  },
];

export const filterStatus = [
  { value: "Active", label: "Active" },
  { value: "Pending", label: "Pending" },
  { value: "Suspend", label: "Suspend" },
];

export const filterRole = [
  { value: "investor", label: "Investor" },
  { value: "seller", label: "Seller" },
  { value: "buyer", label: "Buyer" },
];

export const countryOptions = [
  { value: "Canada", label: "Canada" },
  { value: "USA", label: "USA" },
  { value: "India", label: "India" },
  { value: "Bangladesh", label: "Bangladesh" },
  { value: "France", label: "France" },
  { value: "England", label: "England" },
];
